<?php
//ADDING CUSTOM FIELDS TO WORDCAST USING ADVANCED CUSTOM FIELDS
//USER WILL BE PROMPTED TO INSTALL ADVANCED CUSTOM FIELDS FROM WORDPRESS PLUGIN REP
if(function_exists('acf_add_local_field_group')):

acf_add_local_field_group(array(
	'key' => 'group_5c8179046d079',
	'title' => __('WordCast Channel', 'wordcast'),
	'fields' => array(
		array(
			'key' => 'field_5c817ff49dff8',
			'label' => __('Heads Up!', 'wordcast'),
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __('It is recommended that all of the following fields have content for the best results', 'wordcast'),
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5c9a1be2cb95f',
			'label' => __('Website', 'wordcast'),
			'name' => 'channel_link_wordcast',
			'type' => 'url',
			'instructions' => __('URL to the website where this channel is presented. So make a page for this channel!', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c817b4863fce',
			'label' => __('Channel Description', 'wordcast'),
			'name' => 'channel_description_wordcast',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5c9a1f5e09e0b',
			'label' => __('Language', 'wordcast'),
			'name' => 'channel_language_wordcast',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'af' => __('Afrikaans', 'wordcast'),
				'sq' => __('Albanian', 'wordcast'),
				'eu' => __('Basque', 'wordcast'),
				'be' => __('Belarusian', 'wordcast'),
				'bg' => __('Bulgarian', 'wordcast'),
				'ca' => __('Catalan', 'wordcast'),
				'zh' => __('Chinese', 'wordcast'),
				'hr' => __('Croatian', 'wordcast'),
				'cs' => __('Czech', 'wordcast'),
				'da' => __('Danish', 'wordcast'),
				'nl' => __('Dutch', 'wordcast'),
				'en' => __('English', 'wordcast'),
				'en-us' => __('English (United States)', 'wordcast'),
				'et' => __('Estonian', 'wordcast'),
				'fo' => __('Faeroese', 'wordcast'),
				'fi' => __('Finnish', 'wordcast'),
				'fr' => __('French', 'wordcast'),
				'fr-ca' => __('French (Canada)', 'wordcast'),
				'gl' => __('Galician', 'wordcast'),
				'gd' => __('Gaelic', 'wordcast'),
				'de' => __('German', 'wordcast'),
				'el' => __('Greek', 'wordcast'),
				'haw' => __('Hawaiian', 'wordcast'),
				'hu' => __('Hungarian', 'wordcast'),
				'is' => __('Icelandic', 'wordcast'),
				'in' => __('Indonesian', 'wordcast'),
				'ga' => __('Irish', 'wordcast'),
				'it' => __('Italian', 'wordcast'),
				'ja' => __('Japanese', 'wordcast'),
				'ko' => __('Korean', 'wordcast'),
				'mk' => __('Macedonian', 'wordcast'),
				'no' => __('Norwegian', 'wordcast'),
				'pl' => __('Polish', 'wordcast'),
				'pt' => __('Portuguese', 'wordcast'),
				'ro' => __('Romanian', 'wordcast'),
				'ru' => __('Russian', 'wordcast'),
				'sr' => __('Serbian', 'wordcast'),
				'sk' => __('Slovak', 'wordcast'),
				'sl' => __('Slovenian', 'wordcast'),
				'es' => __('Spanish', 'wordcast'),
				'sv' => __('Swedish', 'wordcast'),
				'tr' => __('Turkish', 'wordcast'),
				'uk' => __('Ukranian', 'wordcast'),
			),
			'default_value' => array(
				0 => 'en',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c817d40f903d',
			'label' => __('Channel Subtitle', 'wordcast'),
			'name' => 'channel_subtitle_wordcast',
			'type' => 'text',
			'instructions' => __('A single, descriptive sentence for your podcast or episode', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 255,
		),
		array(
			'key' => 'field_5c817e149dff4',
			'label' => __('Channel Author', 'wordcast'),
			'name' => 'channel_author_wordcast',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c817d2af903c',
			'label' => __('Channel Copyright', 'wordcast'),
			'name' => 'channel_copyright_wordcast',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c817e2e9dff5',
			'label' => __('Channel Owner Mail', 'wordcast'),
			'name' => 'channel_owner_mail_wordcast',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5cab3220b644d',
			'label' => __('Channel Owner', 'wordcast'),
			'name' => 'channel_owner_wordcast',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c817edc9dff6',
			'label' => __('Explicit', 'wordcast'),
			'name' => 'channel_explicit_wordcast',
			'type' => 'radio',
			'instructions' => __('Does this channel feature explicit content', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cb194ccc62d2',
			'label' => __('Channel Type', 'wordcast'),
			'name' => 'channel_type_wordcast',
			'type' => 'select',
			'instructions' => __('Episodic is the default type of podcasts
Use serial if your podcast is seasonal

Seasons might not show in Google Podcasts or Itunes until 2 or more seasons have been added', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'episodic' => __('Episodic', 'wordcast'),
				'serial' => __('Serial', 'wordcast'),
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5cbf5c68c4c0b',
			'label' => __('Block', 'wordcast'),
			'name' => 'block_channel_wordcast',
			'type' => 'checkbox',
			'instructions' => __('If checked this channel will not be shown in the Google Podcast or Itunes library', 'wordcast'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => __('Block', 'wordcast'),
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcastchannel',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cab394c6025d',
	'title' => __('WordCast Episode', 'wordcast'),
	'fields' => array(
		
		array(
			'key' => 'field_160821wcexlink',
			'label' => __('External link (only mp3 and m4a)', 'wordcast'),
			'name' => 'external_episode_link_wordcast',
			'type' => 'url',
			'instructions' => __('Link to podcast episode file hosted somewhere else. This field or file field <strong><em>MUST</em></strong> be filled', 'wordcast'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		
		array(
			'key' => 'field_5cab60f631f35',
			'label' => __('File', 'wordcast'),
			'name' => 'file_episode_wordcast',
			'type' => 'file',
			'instructions' => __('Supported file types are mp3, m4a, mp4', 'wordcast'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp3, MP3, m4a, M4A, mp4, MP4',
		),
		array(
			'key' => 'field_5cadd97a3ce1a',
			'label' => __('Description', 'wordcast'),
			'name' => 'description_episode_wordcast',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5cbf5abeaff21',
			'label' => __('Episode Subtitle', 'wordcast'),
			'name' => 'episode_subtitle_wordcast',
			'type' => 'text',
			'instructions' => __('A single, descriptive sentence for your podcast or episode', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 255,
		),
		array(
			'key' => 'field_5cae0aefd5662',
			'label' => __('Explicit', 'wordcast'),
			'name' => 'explicit_episode_wordcast',
			'type' => 'radio',
			'instructions' => __('Does this episode feature explicit content', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Yes' => __('Yes', 'wordcast'),
				'No' => __('No', 'wordcast'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cb18f3c8b468',
			'label' => __('Episode Type', 'wordcast'),
			'name' => 'episodetype_episode_wordcast',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => __('Full', 'wordcast'),
				'trailer' => __('Trailer', 'wordcast'),
				'bonus' => __('Bonus', 'wordcast'),
			),
			'default_value' => array(
				0 => 'full',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5cb192d98769c',
			'label' => __('Episode Season', 'wordcast'),
			'name' => 'season_episode_wordcast',
			'type' => 'number',
			'instructions' => __('If your episodes are seasonal and NOT stand-alone episodes
For this to work your channel type must be set to serial', 'wordcast'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5cb194698769d',
			'label' => __('Episode Number', 'wordcast'),
			'name' => 'number_episode_wordcast',
			'type' => 'number',
			'instructions' => __('If your episodes are seasonal and NOT stand-alone episodes
For this to work you your channel type must be set to serial', 'wordcast'),
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cb192d98769c',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5cbf5bedb1e4d',
			'label' => __('Block', 'wordcast'),
			'name' => 'block_episode_wordcast',
			'type' => 'checkbox',
			'instructions' => __('If checked this episode will not be shown in the Google Podcast or Itunes library', 'wordcast'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => __('Block', 'wordcast'),
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcastepisode',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c948fd43ece6',
	'title' => __('WordCast Meta', 'wordcast'),
	'fields' => array(
		array(
			'key' => 'field_5c948fe042c11',
			'label' => __('Channel', 'wordcast'),
			'name' => 'episode_channel_wordcast',
			'type' => 'post_object',
			'instructions' => __('Select the channel this episode belongs to', 'wordcast'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'wordcastchannel',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5ced8bfa93db7',
			'label' => __('Featured Image', 'wordcast'),
			'name' => 'featured_image_wordcast',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 1400,
			'min_height' => 1400,
			'min_size' => '',
			'max_width' => 3000,
			'max_height' => 3000,
			'max_size' => '0.300',
			'mime_types' => 'jpg, jpeg, png',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcastepisode',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ced8e4e75dbf',
	'title' => __('Featured Image', 'wordcast'),
	'fields' => array(
		array(
			'key' => 'field_5ced8e4e7a1e2',
			'label' => __('Image', 'wordcast'),
			'name' => 'featured_image_wordcast',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 1400,
			'min_height' => 1400,
			'min_size' => '',
			'max_width' => 3000,
			'max_height' => 3000,
			'max_size' => '0.300',
			'mime_types' => 'jpg, jpeg, png',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcastchannel',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cc9ba8da6e1c',
	'title' => __('WordCast Channel Side', 'wordcast'),
	'fields' => array(
		array(
			'key' => 'field_5cc9ba9f343c8',
			'label' => __('Add to...', 'wordcast'),
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<a href="https://podba.se/validate/" target="_blank">' . __('Test feed with Podbase Validator') . '</a><br><br>
				<a href="https://play.google.com/music/podcasts/portal/u/0/start#" target="_blank">' . __('Add to Google Play Podcasts', 'wordcast') . '</a><br>
				<a href="https://itunesconnect.apple.com/login" target="_blank">' . __('Add to Itunes Connect', 'wordcast') . '</a><br>
				<a href="https://podcasters.spotify.com/" target="_blank">' . __('Add to Spotify', 'wordcast') . '</a><br>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcastchannel',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;